config/routes.rb
Akhoni::Application.routes.draw do
  devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/settings" => "devise/registrations#edit"
  end

  match "/:merchant_name", :to => "merchants#show", :constraints => lambda{|req| MerchantsRouts::valid?(req.env["REQUEST_URI"]) }
  match "/estores", :to => "merchants#index", :as => "stores"

  match "/:location_id/index_for_facebook/index.php", :to => "deals#index_for_facebook"
  match "/:location_id/index_for_facebook/index.html", :to => "deals#index_for_facebook"

  match "/social-media-likes-featured-deal/:deal_id", :to => "social_media#likes", :as => "social_media_likes"
  match "/social-media-facebook-like-box",  :to => "social_media#fb_like_box", :as => "fb_like_box"
  match "/social-media-google-map/:deal_id",  :to => "deals#google_map", :as => "google_map"

  match "vote", :to => "poll#vote", :as => "vote"

  #ADMIN PANEL
  namespace :manage, :as => 'admin' do
    resources :home, :businesses, :notices, :audits, :payments, :merchants, :mobile_transactions, :corporate_discounts, :presses, :polls ,:categories, :banners
    resources :referrals do
      get :reset_credits, :on => :collection
    end
    resources :coupons do
      post :resend_sms
    end
    resources :notifications do
      get :unsubscribe, :logs, :referral, :on => :collection
      get :assign_users, :preview, :schedule, :send_now, :test, :on => :member
    end
    resources :products do
      get :sizes, :on => :collection
    end
    resources :users do
      put :activate, :suspend, :on=> :member
      get :verify, :on => :collection
      get :stat_report, :on=>:collection
      get :login_as, :on => :collection
      post :login, :on => :collection
    end
    resources :deals do
      get :sort, :on => :collection
      post :update_order, :on => :collection
      get :stat_report, :on=>:collection
    end
    resources :orders do
      post :confirm, :paid, :cancel, :comment
      get :comment, :on => :collection
    end
    resources :payment_summaries do
      get :receive, :on => :collection
    end
    match 'users/verify' => 'users#verify'
    match 'UploadBackgroundImage' => 'home#new_background_image'
    match 'SaveBackgroundImage' => 'home#save_background_image'
    match 'clear_cache' => "settings#clear_cache"
    root :to => 'home#index'
  end

  #MERCHANT PANEL
  namespace :merchant do
    resources :home
    resources :products do
      get :sizes, :on => :collection
    end
    match ':id/coupons', :to => 'coupons#index', :as => 'coupons'
    match ':id/redeemed-coupons', :to => 'coupons#redeemed', :as => 'redeemed_coupons'
    match 'verify-coupon', :to => 'coupons#verify', :as => "coupon_verify"
    match 'merchants_orders', :to => 'report#merchants_orders', :as => "merchants_orders"
    match 'send_approval_notification', :to => 'products#send_approval_notification', :as => "send_approval_notification"
    match 'report(/:action(/:id))', :controller => 'report'
    root :to => 'home#index'
  end

  #STATIC PATH
  match 'getfeatured' => 'businesses#new'
  match 'getfeatured/submit' => 'businesses#create'
  match 'getfeatured/thanks' => 'businesses#thanks'
  match 'about' => 'home#about'
  #match 'HowAkhoniWorks' => 'home#how'
  match 'TermsOfUse' => 'home#terms'
  match 'PrivacyPolicy' => 'home#privacy'
  match 'PageNotFound' => 'home#page_not_found'
  match 'ContactUs' => 'home#contact'
  match 'InstantPurchase' => 'home#credit_card_purchase'
  match 'CashPurchase' => 'home#cash_purchase'
  match 'bkashInstruction' => 'home#bkash_instruction'
  match 'couponOnYourMobile' => 'home#coupon_on_your_mobile'
  match 'career' => 'home#jobs'
  match 'Press' => 'home#press'
  match '/notices/:id' => 'notices#show'
  match ':location/notices/:id' => 'notices#show'
  match ':location/:deal_id/free_coupon' => 'orders#free_coupon'
  match 'digital-mind-2012', :to=> 'home#digital_mind', :as => 'digital_mind'
  match 'deal-corporate-discount/:deal_id/:item_type', :to => 'deals#deal_corporate_discount', :as => "deal_corporate_discount"
  match 'product-corporate-discount/:product_id/:item_type', :to => 'products#product_corporate_discount', :as => "product_corporate_discount"
  match 'decon' => 'home#decon'

  resources :subscriptions, :unsubscribe, :notices
  resources :referrals do
    get :history, :on => :collection
  end

  #FRONT END
  resources :locations, :path => '' do
    get :determine, :on => :collection

    #PRODUCTS
    resources :products do
      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end

    resources :deals, :path => '' do
      get :index_for_facebook, :on => :collection
      get :deals, :to => :sub_deals, :on => :member
      get :past, :on => :collection
      get :expire, :on => :collection

      resources :products do
        resources :orders, {:path => 'buy'} do
          get :checkout, :coupon, :book, :print_coupon, :waiver
          resources :payments do
            post :success, :canceled, :failed, :by_mobile, :referral
            get :error, :incomplete, :invalid
          end
        end
      end

      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "locations#index"

  # See how all your routes lay out with "rake routes"
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match 'manage/orders/:id(.:format)' => 'manage/orders#comment'
  match ':controller(/:action(/:id(.:format)))'
#  match 'report(/:action(/:id))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_blank_layout, :only => [:credit_card_purchase, :cash_purchase, :site_notice, :bkash_instruction, :coupon_on_your_mobile]

  def index
  end

  def digital_mind
     @polls = Poll.live.active
  end

  def about
    about__page_locale = params[:locale].present? ? params[:locale] : I18n.locale
    render 'about_' + about__page_locale.to_s
  end

  def how
    how_akhoni_works_page_locale = params[:locale].present? ? params[:locale] : I18n.locale
    render 'how_' + how_akhoni_works_page_locale.to_s
  end

  def terms
     terms__page_locale = params[:locale].present? ? params[:locale] : I18n.locale
    render 'terms_' + terms__page_locale.to_s
  end

  def privacy
  end

  def page_not_found
  end

  def contact
    contact__page_locale = params[:locale].present? ? params[:locale] : I18n.locale
    render 'contact_' + contact__page_locale.to_s
  end

  def credit_card_purchase
  end

  def cash_purchase
  end

  def site_notice
  end

  def jobs
    contact__page_locale = params[:locale].present? ? params[:locale] : I18n.locale
    render 'jobs_' + contact__page_locale.to_s
  end

  def press
    @presses = Press.latest_first.paginate :per_page => ITEM_PER_PAGE, :page => params[:page]
  end
  def bkash_instruction
  end

  def coupon_on_your_mobile

  end

  private
  def set_blank_layout
    render :layout => false
  end
end

app/controllers/merchant/home_controller.rb
class Merchant::HomeController < ApplicationController
  before_filter :authenticate_user!

  layout 'merchant'

  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_en.html.erb
<% page_title 'About akhoni.com' %>
<div class="terms" style="padding: 10px 0 0 10px; width: 675px;">
  <h3>About akhoni</h3>

  <p>Greetings from akhoni.com Ltd!<br/>

  <p>akhoni.com is an online marketplace featuring discount deals with popular businesses like Internet services,
    Luxurious restaurants, Hotels, Transports, Beauty parlors, Fashion houses, Theme parks, Gymnasiums, Furniture shops,
    Sports & Recreation centers, etc. Our merchant partners offer discounts, date and time specific, on their products,
    and we promote that offer through activation campaigns, emails and sms and obviously our website. We currently have
    a database of around 1.5 lakh consumers which is growing every moment. End of the day, we provide consumers with
    quality and demandable products in cheap, and the businesses with a ton of customers.
    Businesses need customers & profit also, Customers need products but at low cost, AND (what we do?) WE SOLVE THE
    RIDDLE...</p>

  <h3>Our Mission</h3>

  <p>We increase sales of our merchants and create wonderful buying experience for our consumers. We create happiness
    for both our merchants and consumers.</p>
</div>

app/views/home/bkash_instruction.html.erb
<style>
  .description {
      color: #444444;
      font-size: 16px;
  }
  <% if I18n.locale == :bn %>
  .bangla {
      font-family:'SolaimanLipi' !important;
  }
  <% end %>


</style>
<div style="text-align:center;">
<h1 class="bangla"><%= t("PAY_WITH_BKASH")%></h1>
  <p class="description bangla">
    <%= t("TO_PAY_EASILY_FROM_YOUR_MOBILE").html_safe %>

  </p>
  <p class="description bangla"  style="font-variant:small-caps;">
    <%= t("IF_YOU_ARE_ALREADY_A_REGISTERED_USER").html_safe %>

  </p>

  <%= image_tag "/images/bkash_instructions-#{I18n.locale}.png" %>

  <p class="description bangla"  style="font-variant:small-caps;">
    <%= t("CLICK_HERE_TO_KNOW_MORE_ABOUT_BAKSH_PAYMENT_PROCEDURE").html_safe %>
  </p>

</div>

app/views/home/cash_purchase.html.erb
<style type="text/css">
  a {
      color: #E70086;
  }

  a:hover {
      color: #5C0B3A;
  }
</style>
<div style="text-align: center; margin: 50px 50px; color: #555">
  <h1>Pay Cash on Coupon Delivery</h1>
  <p >
      If you don't have credit card, you can still avail the great discounts staying at your home.
      Just order for a coupon online and select the option <strong>"Pay Cash on Coupon Delivery"</strong>.
      For your convenience, we'll deliver the coupon to your home.
    </p>

  <p>Coupon/Product delivery facility is currently available only within Dhaka metropolitan area.</p>

  <p><%= link_to "See our How \"it works\" section", "/HowAkhoniWorks", :target => '_blank' %></p>

</div>

app/views/home/contact_bn.html.erb
<% page_title 'Contact akhoni.com' %>
<div style="padding:0 5px 0 15px;">
  <h2 class="bd_contacts" style="padding: 20px 0px 0px;">যোগাযোগের তথ্য </h2>
  <hr/>
  <div id="intro">এখনি ডট কম সাইট ব্যবহারে সমস্যা হচ্ছে অথবা আপনি কি কোন বিজনেস ডিল নিয়ে কথা বলতে ইচ্ছুক ? তাহলে নিচের তথ্য ব্যবহার করে আপনি আমাদের কাছে পৌঁছে যেতে পারবেন।</div>
  <br />

  <table  width="100%" cellspacing="5" >
    <tr>
      <td class="bd_contacts" width="45" valign="top"><strong>ঠিকানা</strong></td>
      <td valign="top"><strong>:</strong></td>
      <td class="bd_contacts" valign="top">House No. 47 (3rd Floor), Road No. 6, Block C, Niketon Housing Society,<br /> Gulshan-1, 1212 Dhaka, Bangladesh<br /><br /></td>
    </tr>
    <tr>
      <td class="bd_contacts" valign="top"><strong>ই-মেইল</strong></td>
      <td valign="top"><strong>:</strong></td>
      <td valign="top"><a href="mailto:<%=h SITE_CONFIG['system_email']['contact']%>" style="font-weight: normal;"><%=h SITE_CONFIG['system_email']['contact']%></a><br /><br /></td>
    </tr>
    <tr>
      <td class="bd_contacts" valign="top"><strong>ফোন </strong></td>
      <td valign="top"><strong>:</strong></td>
      <td valign="top"><%=h SITE_CONFIG['office_phone']%><br/><%=h SITE_CONFIG['hotline_number']%></td>
    </tr>
  </table>
</div>

app/views/home/coupon_on_your_mobile.html.erb
<style>
  .description {
      color: #444444;
      font-size: 16px;
  }


</style>
<div style="text-align:center;">
    <%= image_tag "/images/Get-Coupon-On-Your-Mobile-Phone-#{I18n.locale}.png", :border => 0 %>
</div>

app/views/home/credit_card_purchase.html.erb
<style>
  .description {
      color: #444444;
      font-size: 16px;
  }


</style>
<div style="text-align:center;">
    <%= image_tag "/images/pop_up_writing_for_credit-#{I18n.locale}.png", :border => 0 %>
</div>

app/views/home/decon.html.erb
<% page_title 'Decon Developments Limited' %>
<div class="title page-header">
  <h1> Decon Developments Limited </h1>
</div>

<div class="terms" style="padding: 10px 0 0 10px; width: 675px;">

  <%= image_tag "/images/decon-banner.jpg", :alt => 'decon banner', :style =>'padding-left:35px' %>
  <br/>
  <%= image_tag "/images/decon.gif", :alt => 'decon', :style =>'padding-left:35px'%>
  <br/>  <br/>

  <p style="padding-left: 10px">Decon Developments Ltd. has already been working in various numbers of apartments, commercial and land projects
    in around Dhaka. Decon Developments Ltd. is not only to deliver apartment of schedule but also to maintain the highest-grade
    construction quality that has gained trust and respect in customer.</p>

  <p style="padding-left: 10px">Since inception, Decon Developments Ltd. has been actively contributing to the national economy by way of effective utilization
    of resources, using raw materials, production and marketing high quality products at the most competitive prices and creating
    employment opportunities.</p>

  <h3 style="padding-left: 10px">Contact : </h3>

  <p style="padding-left: 10px">
  DECON DEVELOPMENTS LIMITED<br/>
  House -43, Avenue - 5, Block-A,Section- 6,<br/>
  Mirpur,Dhaka-1216,<br/>
  Bangladesh<br/>
  Phone: 88-02-8060746, 8054289,<br/>
  Mobile: 01971000152, 01971000153<br/>
  E-mail: info@decon.com.bd<br/>
  For more information, please visit: <a href="http://decon.com.bd/" style="color:blue;" target="_blank">http://decon.com.bd</a><br/>
  Connect with us at facebook:  <a href="https://www.facebook.com/Decon.development" style="color:blue;" target="_blank" >https://www.facebook.com/Decon.development</a> </p>
</div>

app/views/home/digital_mind.html.erb
<div class="digital-mind-main">
  <div class="heading">
    <%= image_tag('/images/top-banner.png') %>
  </div>
  <div class="digital-mind-left">


    <div class="digital-mind-left"><a href="#" title=""><%= image_tag('/images/grand-prize.png') %></a></div>

    <div class="digital-mind-left">
      <a href="#" title="educational books"><%= image_tag('/images/real-life-challenge.png') %></a></div>

    <div class="digital-mind-left">
      <a href="#" title="educational books"><%= image_tag('/images/grooming-session.png') %></a></div>
    <div class="digital-mind-left">
      <a href="#" title="educational books"><%= image_tag('/images/certificate.png') %></a>
    </div>


    <div style="clear: both;"></div>
    <div id="poll" style="padding: 20px 0 35px 0;">

        <% form_for '', :url => vote_url, :html => {:method => :get, :id => 'poll_form'} do |f| %>
            <% @polls.each do |poll| %>
                <strong style="margin-bottom: 10px;width: 585px;float: left;"><%= poll.question %></strong>
                <% poll.poll_options.each do |poll_option| %>
                    <% vote_casted = poll.vote_casted?(current_user) %>
                  <table style="clear: both;">
                    <tr>
                      <td>
                        <%= radio_button_tag("poll_options[#{poll.id}]", poll_option.id, false, :class => "vote_#{poll.id}", :disabled => vote_casted) %>
                      </td>
                      <td style="background: #EEEEEE;min-width: 360px" class="<%= !vote_casted ? 'active-poll-option' : '' %>">
                        <%= "#{poll_option.option}" %>
                      </td>
                      <td style="background: #EEEEEE;min-width: 60px;">
                        <%= poll_option.vote_count %> <%= poll_option.vote_count > 1 ? "votes" : "vote" %>
                      </td>
                    </tr>
                  </table>
                <% end %>
            <% end %>
        <% end %>

    </div>

  </div>
  <div class="digital-mind-content-full">

    <% if I18n.locale == :bn %>
        <style type="text/css">
            .digital-mind-content-full p {
                font-family: 'SolaimanLipi';
                font-size: 17px;
            }
        </style>
        <p>
          নিঃসন্দেহে আমরা ছুটে চলেছি এক ডিজিটাল বিপ্লবের মধ্য দিয়ে।কিন্তু ডিজিটাল যুগের বাসিন্দা হিসেবে আমরা কতটা
          প্রস্তুত?</p><br/>

        <p>বাংলাদেশে এই প্রথমবারের মত <%= link_to 'এখনই ডট কম', root_url %> আয়োজন করেছে ”এখনই ডট কম-ডিজিটাল মাইন্ড’
          শিরোনামের এক অনন্য
          প্রতিযোগীতার। </p><br/>

        <p>প্রতিযোগীতাটি অনুষ্ঠিত হবে ৩টি ধাপে।প্রথম ধাপে আমরা আপনার ইউনিভার্সিটিতে একটি সেমিনার এর আয়োজন করবো।সেমিনারে
          বর্তমান ডিজিটাল দুনিয়া এবং প্রতিযোগীতা সম্পর্কে বিস্তারিত আলোচনা করা হবে। সেমিনার শেষে একটি সংক্ষিপ্ত পরীক্ষা
          নেয়া হবে। </p><br/>

        <p>ছাত্র-ছাত্রীদেরকে তাদের জীবন বৃত্তান্ত সংগে নিয়ে আসার জন্য বিশেষভাবে অনুরোধ করা হচ্ছে। পরীক্ষার নম্বর ও জীবন
          বৃত্তান্ত বাছাইয়ের মাধ্যমে প্রতি ইউনিভার্সিটি থেকে ৫ জনের একটি দল মনোনীত করা হবে।</p><br/>

        <p>দ্বিতীয় ধাপে, এই ৫ জনের দলকে একটি সংক্ষিপ্ত প্রশিক্ষণের মধ্যে দিয়ে যেতে হবে।বর্তমানে দেশের সফল ডিজিটাল গুরুরা
          এই প্রশিক্ষণ দেবেন।প্রশিক্ষণ শেষে প্রতিযোগীরা নিজ নিজ ইউনিভার্সিটিতে বিভিন্নভাবে প্রচার প্রচারণা চালাবেন এবং
          কিভাবে বাংলাদেশে একটি সফল ই-কমার্স ব্যবসায়কে জনপ্রিয় করা যায় সে ব্যাপারে কাজ করবেন। </p><br/>

        <p>তৃতীয় ধাপে প্রতিযোগীদের নিয়ে একটি ফাইনাল গালা রাউন্ড অনুষ্ঠিত হবে।এতে প্রতিযোগীরা দেশের সফল মার্কেটিং এবং
          এ্যাডভার্টাইজিং গুরুদের সামনে প্রেজেন্টেশন করবেন।বিজয়ী দলকে ক্রেস্ট, সার্টিফিকেট, আকর্ষনীয় উপহার এবং শীর্ষ
          কোম্পানীগুলোতে ইন্টার্নশীপ সাপোর্ট এর সুযোগ দেয়া হবে।</p><br/>

        <p>যে কোন বিভাগের ছাত্র-ছাত্রীরাই সেমিনার এ অংশ নিতে পারবেন। প্রতিযোগীতার ব্যাপারে যে কোন তথ্যের জন্য 01198 00
          87 80 এই নম্বরে ফোন করুন।</p>
    <% end %>
    <% if I18n.locale == :en %>
        <p>
          There is no doubt that we are going through a DIGITAL revolution. So, as a proud citizen of Digital World, ARE
          WE READY...??
        </p>
        <br/>

        <p>
          <%= link_to 'Akhoni.com', root_url %> brings this opportunity first time in Bangladesh to explore the world of
          digital marketing for our future marketers. We have arranged an Inter University Digital Marketing Contest
          titled Akhoni.com- Digital Mind 2012.
        </p>
        <br/>

        <p>
          The contest will run in 3 phases. In phase 1, we will arrange a seminar in your university. The seminar will
          cover topics such as digital marketing trends and details about the contest. After the seminar, there will be
          a short written test. Students are requested to bring their CVs to sit for the test. 5 students from each
          university will be selected based on the test result and CV screening.
        </p>
        <br/>

        <p>
          In phase 2, these 5 students from each university will form a group and will be provided a short grooming
          session conducted by Industry experts on Digital Marketing. After the grooming session, students will run
          campaign in the university as well as online and will show their effort about popularizing eCommerce in
          Bangladesh.
        </p>
        <br/>

        <p>
          In phase 3, there will be a FINAL GALA round in which participants will make a presentation in front of the
          judges. Marketing and Advertising Leaders and Gurus of the industry will be present as judges. The winners
          will get crests, certificates, attractive gifts and support in getting internships in top companies
        </p>
        <br/>

        <p>
          Students from all disciplines are encouraged to join the seminar. For more info, please call us on
          01198 00 87 80
        </p>
        <br/>
    <% end %>

  </div>

</div>

app/views/home/how_en.html.erb
<% page_title t('HOW_AKHONI_WORKS') %>
<div class="terms">
  <h1 class="page_title" style="width:600px">How Akhoni.com works?</h1>
  <!--a style="width:50px;float:right;font-weight:bold;color:#5C0B3A;font-size:18px" href="<%#= root_url %>HowAkhoniWorks?locale=bn">বাংলা</a-->

  <div class="page_subtitle" style="margin: 0.5em 0.5 1em 0em;"><p>
    Akhoni offers discounts upto 90% in your city on popular businesses like Dining, Travel, Entertainment, Movies, Spa,
    Healthcare services, Fitness centers, Beauty parlors and lot more
  </p></div>
  <%= image_tag 'how_it_works_discount.gif', :width => 685 %>
  <dl class="help_section">
    <dt>Step One: <span>Sign Up</span></dt>
    <dd>
      <table width="100%">
        <tr>
          <td style="width: 150px;"><%= image_tag 'subscribe.png' %></td>
          <td>
            Sign up with Akhoni.com to get crazy discount notifications right in your email inbox.
            Sign up FREE <%= link_to "here", new_user_registration_path %>.
          </td>
        </tr>
      </table>
    </dd>
    <dt>Step Two: <span>Buy and Receive Coupon</span></dt>
    <dd>
      <table width="100%">
        <tr>
          <td style="width: 150px;">
            <br/>
            <%= image_tag 'buy_now.png' %>
            <br/><br/>
            <%= image_tag 'voucher.png' %>
          </td>
          <td>
            <ul style="margin: 0px 0px 0px -20px; ">
              <li>To purchase a deal, click on <b>“View details & Buy”</b> / <b>“Buy Now”</b> button.</li>
              <li><b>"Instant Pay"</b> Option: Safely pay with your Visa/ MasterCard/ DBBL Nexus card and from mobile phone through bKash. You’ll receive your coupon instantly in your email inbox and on your mobile phone through sms.

              </li>
              <li><b>"Pay on Coupon Delivery"</b> Option: Click "Pay cash on coupon delivery" if you
                want to pay later. This option lets you pay when you receive the coupon from our
                delivery men at your home or at your preferred location. There is NO additional
                charge for the delivery of coupon - pay only for the coupon.
              </li>
              <li><b>"Collect from Akhoni.com Office"</b> Option: You can also collect your coupon
                from Akhoni.com office [House No. 47 (3rd Floor), Road No. 6, Block C, Niketon Housing Society, Gulshan-1, 1212 Dhaka, Bangladesh] and pay there.
              </li>
            </ul>
          </td>
        </tr>
      </table>
    </dd>
    <dt>Step Three: <span>Show Coupon</span></dt>
    <dd>
      <table width="100%">
        <tr>
          <td style="width: 150px;">
            <br/>
            <%= image_tag 'merchant.png' %>
          </td>
          <td>Show your coupon to the merchant at his/her outlet and enjoy the discount.</td>
        </tr>
      </table>
    </dd>
  </dl>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/press.html.erb
<% page_title "Press Coverage - Akhoni.com" %>

<div class="title page-header">
  <h1><%= t("PRESS_COVERAGE") %></h1>
</div>



<div class="press-release">
  <br/><br/>
  <% @presses.each do |press| %>
      <!--New div Start -->
      <div class="news-box">

        <div class="press-l">
          <div class="press-head">
            <a href="<%= press.url %>" target="_blank">
              <span class="news-title"><%= h press.title %></span>
            </a>

          </div>
          <div class="press-txt"><%= h press.description %></div>

        </div>

        <div class="press-left">
          <div class="date"><%= show_date(press.published_at) %></div>
          <div class="img">
            <%= image_tag press.logo.url(:medium) %>
          </div>
        </div>
      </div>
  <% end %>
  <div style="clear: both;"></div>
  <%= will_paginate @presses %>
</div>