config/routes.rb
Akhoni::Application.routes.draw do
  devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/settings" => "devise/registrations#edit"
  end

  match "/:merchant_name", :to => "merchants#show", :constraints => lambda{|req| MerchantsRouts::valid?(req.env["REQUEST_URI"]) }
  match "/estores", :to => "merchants#index", :as => "stores"

  match "/:location_id/index_for_facebook/index.php", :to => "deals#index_for_facebook"
  match "/:location_id/index_for_facebook/index.html", :to => "deals#index_for_facebook"

  match "/social-media-likes-featured-deal/:deal_id", :to => "social_media#likes", :as => "social_media_likes"
  match "/social-media-facebook-like-box",  :to => "social_media#fb_like_box", :as => "fb_like_box"
  match "/social-media-google-map/:deal_id",  :to => "deals#google_map", :as => "google_map"

  match "vote", :to => "poll#vote", :as => "vote"

  #ADMIN PANEL
  namespace :manage, :as => 'admin' do
    resources :home, :businesses, :notices, :audits, :payments, :merchants, :mobile_transactions, :corporate_discounts, :presses, :polls ,:categories, :banners
    resources :referrals do
      get :reset_credits, :on => :collection
    end
    resources :coupons do
      post :resend_sms
    end
    resources :notifications do
      get :unsubscribe, :logs, :referral, :on => :collection
      get :assign_users, :preview, :schedule, :send_now, :test, :on => :member
    end
    resources :products do
      get :sizes, :on => :collection
    end
    resources :users do
      put :activate, :suspend, :on=> :member
      get :verify, :on => :collection
      get :stat_report, :on=>:collection
      get :login_as, :on => :collection
      post :login, :on => :collection
    end
    resources :deals do
      get :sort, :on => :collection
      post :update_order, :on => :collection
      get :stat_report, :on=>:collection
    end
    resources :orders do
      post :confirm, :paid, :cancel, :comment
      get :comment, :on => :collection
    end
    resources :payment_summaries do
      get :receive, :on => :collection
    end
    match 'users/verify' => 'users#verify'
    match 'UploadBackgroundImage' => 'home#new_background_image'
    match 'SaveBackgroundImage' => 'home#save_background_image'
    match 'clear_cache' => "settings#clear_cache"
    root :to => 'home#index'
  end

  #MERCHANT PANEL
  namespace :merchant do
    resources :home
    resources :products do
      get :sizes, :on => :collection
    end
    match ':id/coupons', :to => 'coupons#index', :as => 'coupons'
    match ':id/redeemed-coupons', :to => 'coupons#redeemed', :as => 'redeemed_coupons'
    match 'verify-coupon', :to => 'coupons#verify', :as => "coupon_verify"
    match 'merchants_orders', :to => 'report#merchants_orders', :as => "merchants_orders"
    match 'send_approval_notification', :to => 'products#send_approval_notification', :as => "send_approval_notification"
    match 'report(/:action(/:id))', :controller => 'report'
    root :to => 'home#index'
  end

  #STATIC PATH
  match 'getfeatured' => 'businesses#new'
  match 'getfeatured/submit' => 'businesses#create'
  match 'getfeatured/thanks' => 'businesses#thanks'
  match 'about' => 'home#about'
  #match 'HowAkhoniWorks' => 'home#how'
  match 'TermsOfUse' => 'home#terms'
  match 'PrivacyPolicy' => 'home#privacy'
  match 'PageNotFound' => 'home#page_not_found'
  match 'ContactUs' => 'home#contact'
  match 'InstantPurchase' => 'home#credit_card_purchase'
  match 'CashPurchase' => 'home#cash_purchase'
  match 'bkashInstruction' => 'home#bkash_instruction'
  match 'couponOnYourMobile' => 'home#coupon_on_your_mobile'
  match 'career' => 'home#jobs'
  match 'Press' => 'home#press'
  match '/notices/:id' => 'notices#show'
  match ':location/notices/:id' => 'notices#show'
  match ':location/:deal_id/free_coupon' => 'orders#free_coupon'
  match 'digital-mind-2012', :to=> 'home#digital_mind', :as => 'digital_mind'
  match 'deal-corporate-discount/:deal_id/:item_type', :to => 'deals#deal_corporate_discount', :as => "deal_corporate_discount"
  match 'product-corporate-discount/:product_id/:item_type', :to => 'products#product_corporate_discount', :as => "product_corporate_discount"
  match 'decon' => 'home#decon'

  resources :subscriptions, :unsubscribe, :notices
  resources :referrals do
    get :history, :on => :collection
  end

  #FRONT END
  resources :locations, :path => '' do
    get :determine, :on => :collection

    #PRODUCTS
    resources :products do
      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end

    resources :deals, :path => '' do
      get :index_for_facebook, :on => :collection
      get :deals, :to => :sub_deals, :on => :member
      get :past, :on => :collection
      get :expire, :on => :collection

      resources :products do
        resources :orders, {:path => 'buy'} do
          get :checkout, :coupon, :book, :print_coupon, :waiver
          resources :payments do
            post :success, :canceled, :failed, :by_mobile, :referral
            get :error, :incomplete, :invalid
          end
        end
      end

      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "locations#index"

  # See how all your routes lay out with "rake routes"
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match 'manage/orders/:id(.:format)' => 'manage/orders#comment'
  match ':controller(/:action(/:id(.:format)))'
#  match 'report(/:action(/:id))'
end

app/controllers/merchant/coupons_controller.rb
class Merchant::CouponsController < ApplicationController
  before_filter :authenticate_user!, :authorize_merchant
  layout 'merchant'

  def index
    merchant_id = params[:id].to_i
    @merchant = Merchant.find_by_id(merchant_id)
    if @merchant.nil? || !@merchant.users.include?(current_user)
      #raise CanCan::AccessDenied.new(MESSAGE_UNAUTHORIZED)
      redirect_to root_url
      return
    end

    # A merchant will see blank coupon page until he gives a valid coupon code
    session[:coupon_search] = {"order_deal_id_or_order_deal_parent_id_equals"=>"", "order_product_id_equals"=>"", "security_code_coupon_contains"=>"xxxxxxxx"}

    if params[:search].present?
      session[:coupon_search] = params[:search]
      session[:coupon_page] = 1
    end
    session[:coupon_page] = params[:page] if params[:page].present?

    @deals = @merchant.deals.parent_deal
    @products = @merchant.products
    redirect_to :controller => 'merchant/home', :action => :index and return if (@deals.size + @products.size) == 0

    conditions = prepare_conditions
    @search = Coupon.for_all(conditions).confirmed.not_canceled.search((session[:coupon_search] if session[:coupon_search].present?))
    @coupons = @search.all.paginate(:page => session[:coupon_page], :per_page => 100)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @coupons }
    end
  end

  def verify
    result = Hash.new
    coupon = Coupon.find_by_id(params[:coupon_id].to_i)
    verify_code = params[:verification_code].to_i

    if coupon.nil?
      result = {:status => 'FAILED', :data => 'Order not found'}
    elsif !coupon.redeemed_ability?(current_user)
      result = {:status => 'UNAUTHORIZED', :data => "You don't have permission to access the data"}
    elsif coupon.log_failed_redeems.length > Coupon::MAX_REDEEM_ATTEMPT
      result = {:status => 'FAILED', :data => 'The order is locked due to repeated redeem attempts'}
    elsif coupon.security_code_verification.present? && coupon.security_code_verification != verify_code
      if coupon.log_failed_redeems.length == Coupon::MAX_REDEEM_ATTEMPT
        result = {:status => 'SUCCESS', :data => render_to_string(:partial => 'row_order', :locals => {:coupon => coupon})}
      else
        result = {:status => 'FAILED', :data => "Verification code mismatched"}
      end
      LogFailedRedeem.create(:user => current_user, :coupon => coupon)
    else
      coupon.redeemed_at = Time.now
      coupon.redeemed_by_user = current_user
      coupon.save
      result = {:status => 'SUCCESS', :data => render_to_string(:partial => 'row_order', :locals => {:coupon => coupon})}
    end

    render :json => result
  end

  def redeemed
    @merchant = Merchant.find_by_id(params[:id].to_i)
    @deals = @merchant.deals.parent_deal
    @products = @merchant.products
    session[:coupon_search] = nil
    if params[:search].present?
      session[:coupon_search] = params[:search]
      session[:coupon_page] = 1
    end
    session[:coupon_page] = params[:page] if params[:page].present?

    conditions = prepare_conditions
    @search = Coupon.for_all(conditions).redeemed_coupons.search((session[:coupon_search] if session[:coupon_search].present?))
    @coupons = @search.all.paginate(:page => session[:coupon_page], :per_page => 100)
  end


  private

  def prepare_conditions
    ids = {}
    ids[:deal] = @deals.map { |deal| deal.id }
    ids[:product] = @products.map { |product| product.id }
    conditions = []
    conditions << "deals.id in (#{ids[:deal].join(', ')}) or deals.parent_id in (#{ids[:deal].join(', ')}) " if ids[:deal].any?
    conditions << "products.id in (#{ids[:product].join(', ')})" if ids[:product].any?
    return conditions
  end

end

app/controllers/merchant/home_controller.rb
class Merchant::HomeController < ApplicationController
  before_filter :authenticate_user!

  layout 'merchant'

  def index
  end

end

app/controllers/merchant/products_controller.rb
class Merchant::ProductsController < ApplicationController
  before_filter :authenticate_user!
  after_filter lambda { |controller| controller.update_bangla_for(@product) }, :only => [:create, :update]

  layout 'merchant'

  def index
    @products = Array.new
    Product.not_deal_specific.search(params[:search]).each do |product|
      @products << product if product.merchants_product?(current_user)
    end
    @products = @products.paginate(:page => params[:page], :per_page => ITEM_PER_PAGE)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @products }
    end
  end

  def new
    @product = Product.new
    @product.status='pending'
    @product.quantity=0
  end

  def create
    @product = Product.new(params[:product])
    @product.status='pending'
    check_merchant_authorization
    begin
      @product.save!
       @product.update_attribute(:quantity, @product.product_sizes.sum(:quantity).to_i) if @product.product_sizes.present?
      redirect_to merchant_products_path(), :notice => 'Product was successfully created.'
    rescue Exception => error
      logger.error "Error:: #{error.message}"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    if @product.status == 'approved'
      redirect_to root_url, :notice => 'You have not permission to do that' and return
    end
    check_merchant_authorization
  end

  def update
    @product = Product.find(params[:id])
    check_merchant_authorization
    begin
      @product.update_attributes!(params[:product])
       @product.update_attribute(:quantity, @product.product_sizes.sum(:quantity).to_i) if @product.product_sizes.present?
      redirect_to merchant_products_path(), :notice => 'Product information updated successfully'
    rescue Exception => error
      logger.error "Error:: #{error.message}"
      render :edit
    end
  end

  def sizes
    product_id = params[:id].to_i
    @product = Product.find(params[:id].to_i) if product_id > 0
    category = Category.find(params[:category_id])
    @sizes = category.present? ? category.sizes : Size.all

    render :layout => false
  end

  def send_approval_notification
    product_id = params[:product_id].to_i
    product = Product.find(product_id)
    if !product.merchants_product?(current_user)
       page_not_found(product)
    end

    MerchantMailer::send_approval_notification(product,current_user).deliver!
    redirect_to merchant_products_url, :notice => "An approval email notification has been sent to admin!"
  end

  protected
  def check_merchant_authorization
    merchant_id = @product.merchant.id
    merchant = Merchant.find(merchant_id)
    if !merchant.manager?(current_user)
      redirect_to root_url, :notice => 'You have not permission to do that' and return
    end
  end

end

app/controllers/merchant/report_controller.rb
class Merchant::ReportController < ApplicationController
  before_filter :authenticate_user!, :authorize_merchant
  MESSAGE_UNAUTHORIZED = "Not authorized!"
  layout 'merchant'

  def index
    @merchants = current_user.merchants

    if @merchants.size == 0
       redirect_to root_url
      return
    elsif @merchants.size == 1
      redirect_to merchant_coupons_url(:id => @merchants.first)
      return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @merchants }
    end
  end


  def merchants_orders
      prepare_search_criteria()
      ids = current_user.merchants.collect{|p| p.id}
      deal_ids = Deal.for_merchant(ids).collect{|p| p.id}
      product_ids = Product.for_merchant(ids).collect{|p| p.id}
      @search = Order.joins(:payments).according_sort.specific_orders(deal_ids,product_ids).search((session[:order_search] if session[:order_search].present?))
      @orders = @search.all
      @orders = @orders.uniq
      @orders = @orders.paginate(:page => session[:order_page], :per_page => ITEM_PER_PAGE)
      render :file => '/merchant/report/merchants_orders.html.erb' and return
  end

  private
      def prepare_search_criteria()
        if params[:search].present?
          params[:search].delete(:confirmed_by_greater_than_or_equal_to) if params[:search][:confirmed_by_greater_than_or_equal_to].to_i == 0
          params[:search].delete(:is_notified_is_true) if params[:search][:is_notified_is_true].to_i == 0
          params[:search].delete(:canceled_by_greater_than_or_equal_to) if params[:search][:canceled_by_greater_than_or_equal_to].to_i == 0
          params[:search].delete(:canceled_by_less_than) if params[:search][:canceled_by_less_than].to_i == 0
          params[:search].delete(:deal_id_greater_than_or_equal_to) if params[:search][:deal_id_greater_than_or_equal_to].to_i == 0
          params[:search].delete(:deal_id_less_than) if params[:search][:deal_id_less_than].to_i == 0
          params[:search].delete(:product_id_greater_than_or_equal_to) if params[:search][:product_id_greater_than_or_equal_to].to_i == 0
          params[:search].delete(:product_id_less_than) if params[:search][:product_id_less_than].to_i == 0

          if params[:select_delivery_date].nil?
            params[:search].delete(:delivery_date_greater_than_or_equal_to)
            params[:search].delete(:delivery_date_less_than_or_equal_to)
          end

          session[:order_search] = params[:search]
          session[:order_page] = 1
        end

        session[:order_page] = params[:page] if params[:page].present?
      end


end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def show
    @merchant = Merchant.find_by_url_name(params[:merchant_name])
    redirect_to root_url if !@merchant.has_store_enabled?
  end

  def index
    @merchants = Merchant.enabled
  end
end

app/helpers/merchant/products_helper.rb
module Merchant::ProductsHelper
  def show_product_sizes(product)
    sizes = Array.new
    product.sizes.each do |size|
      sizes << size.name
    end
    return sizes.join(', ')
  end
end

app/helpers/merchant/report_helper.rb
module Merchant::ReportHelper
  def link_to_coupons_page(merchant)
    return merchant.name if (merchant.deals.present? && merchant.deals.size == 0) ||(merchant.products.present? && merchant.products.size == 0 )
    return link_to merchant.name, merchant_coupons_url(:id => merchant)

  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
  def render_featured_merchants
    merchants = Merchant.featured
    if merchants.any?
      render :partial => "merchants/featured_merchants", :locals => {:merchants => merchants}
    end
  end
end

app/views/merchants/_featured_merchants.html.erb
<% if merchants.present? && merchants.size > 0 %>
    <div class="multiple-deal">
      <div class="multiple-deal-wrap">
        <div class="multiple-deal-content">
          <h2 class="multiple-deal-title">
            <%= t("FEATURED_STORES")%>
            <span style="float: right;">
                  <%= link_to t("ALL_STORES"), stores_url, :style => "color: #E70086" %>
                </span>
          </h2>

          <div style="width: 665px;padding: 15px;float: left;">
            <% merchants.each_with_index do |merchant,index| %>
                <div style="width:108px;height:105px;float: left;margin: 0 20px 10px 0;border: 1px solid #EEEEEE">
                  <div class="show-product-details_link">
                    <a href="/<%= merchant.url_name %>"><%= merchant.name %></a>
                  </div>
                  <div class="travel_image_hover">
                    <a href="/<%= merchant.url_name %>"><%= image_tag merchant.logo.url(:thumb) %></a>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/merchants/_products.html.erb
<% if products.size > 0 %>
    <div class="multiple-deal">
      <div class="multiple-deal-wrap">
        <div class="multiple-deal-content">
          <h2 class="multiple-deal-title" style="border-radius: 0;margin-top: 20px">
            <%= t("ALL_PRODUCTS")%>
          </h2>


          <div style="clear:both;"></div>
          <table width="95%" cellspacing="12" style="background-color:#FCFAFB" id="featured_products">
            <%
               index = 0
            %>
            <% products.each do |product| %>
                <% if index%3 == 0 %>
                    <tr>
                <% end %>
                <td style="border: 1px solid #EEEEEE">
                  <div style="width:210px;">
                    <div class="show-product-details_link">
                      <%= show_product_details_link(product) %>
                    </div>
                    <div style="clear:both"></div>
                    <div class="product_image_hover">
                      <div class="product_image_hover_wrapper">
                        <%= show_product_details_link(product, "<img src='/images/details_buy.png'/>", 'multiple-product') %>
                      </div>
                      <%= show_picture(product, :product_medium) %>
                      <% if !product.enabled? || product.booked? %>
                          <%= image_tag '/images/sold-out.png', :style => "position:relative;top:-131px;left:103px;width:100px;" %>
                      <% end %>
                    </div>
                    <div style="clear:both"></div>
                  </div>
                  <div class="products_prices">
                    <div style="float:left">
                      <span style="text-decoration: line-through;color: #e70086;">Tk.<%= product.actual_price.to_bddigit %> </span>
                    </div>
                    <div style='float:left;margin-left:8px;'>
                      <span style="color: #e70086;" class="tk">Tk.<%= product.discounted_price.to_bddigit %></span>
                    </div>
                    <div class='discount-multiple-product'>
                      <span><%= h product.discount.to_bddigit %>% off </span>
                    </div>
                    <div class="corporate-extra-discount" item_id="<%= product.id %>" item_type="product" style="clear: both;font-size: 14px;width: 205px;overflow: hidden;height: 20px;">
                    </div>
                  </div>
                </td>
                <% if index%3 > 2 %>
                    </tr>
                <% end %>
                <% index =index+1 %>
            <% end %>
          </table>
        </div>
      </div>
    </div>
<% end %>

app/views/merchants/index.html.erb
    <div class="multiple-deal">
      <div class="multiple-deal-wrap">
        <div class="multiple-deal-content">
          <h2 class="multiple-deal-title">
            <%= t("ALL_STORES")%>
            <span style="float: right;">
                  <%#= link_to "All Stores", stores_url, :style => "color: #E70086" %>
                </span>
          </h2>
          <div style="width: 665px;padding: 15px;float: left;">
            <% @merchants.each_with_index do |merchant,index| %>
                <div style="width:108px;height:105px;float: left;margin: 0 20px 10px 0;border: 1px solid #EEEEEE">
                  <div class="show-product-details_link">
                    <a href="/<%= merchant.url_name %>"><%= merchant.name %></a>
                  </div>
                  <div class="travel_image_hover">
                    <a href="/<%= merchant.url_name %>"><%= image_tag merchant.logo.url(:thumb) %></a>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/merchants/show.html.erb
<div>
<div class="title page-header">
  <h1 class="bangla"><%= @merchant.name %></h1>
</div>


<table style="margin: 0">
  <tr>
    <td>
      <%= image_tag @merchant.banner.url(:big) if @merchant.banner %>
    </td>
    <!--<td valign="top" style="padding-left: 10px">
      &lt;!&ndash;<strong class="bangla"><%= t("ADDRESS")%></strong>: <span class="bangla"><%#= @merchant.address %></span>  <br />
      <strong class="bangla"><%= t("PHONE")%></strong>: <%#= @merchant.contract_number %>  <br />
      <strong class="bangla"><%= t("EMAIL")%></strong>: <%#= @merchant.email %>  <br />
      <strong class="bangla"><%= t("WEBSITE")%></strong>: <a style="text-decoration: underline" target="_blank" href="http://<%#= @merchant.website %>"><%#= @merchant.website %></a>&ndash;&gt;
    </td>-->
  </tr>
</table>

</div>


 <%= render :partial => "merchants/products", :locals => {:products => @merchant.approved_products.order('created_at DESC')  } %>