config/routes.rb
Akhoni::Application.routes.draw do
  devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/settings" => "devise/registrations#edit"
  end

  match "/:merchant_name", :to => "merchants#show", :constraints => lambda{|req| MerchantsRouts::valid?(req.env["REQUEST_URI"]) }
  match "/estores", :to => "merchants#index", :as => "stores"

  match "/:location_id/index_for_facebook/index.php", :to => "deals#index_for_facebook"
  match "/:location_id/index_for_facebook/index.html", :to => "deals#index_for_facebook"

  match "/social-media-likes-featured-deal/:deal_id", :to => "social_media#likes", :as => "social_media_likes"
  match "/social-media-facebook-like-box",  :to => "social_media#fb_like_box", :as => "fb_like_box"
  match "/social-media-google-map/:deal_id",  :to => "deals#google_map", :as => "google_map"

  match "vote", :to => "poll#vote", :as => "vote"

  #ADMIN PANEL
  namespace :manage, :as => 'admin' do
    resources :home, :businesses, :notices, :audits, :payments, :merchants, :mobile_transactions, :corporate_discounts, :presses, :polls ,:categories, :banners
    resources :referrals do
      get :reset_credits, :on => :collection
    end
    resources :coupons do
      post :resend_sms
    end
    resources :notifications do
      get :unsubscribe, :logs, :referral, :on => :collection
      get :assign_users, :preview, :schedule, :send_now, :test, :on => :member
    end
    resources :products do
      get :sizes, :on => :collection
    end
    resources :users do
      put :activate, :suspend, :on=> :member
      get :verify, :on => :collection
      get :stat_report, :on=>:collection
      get :login_as, :on => :collection
      post :login, :on => :collection
    end
    resources :deals do
      get :sort, :on => :collection
      post :update_order, :on => :collection
      get :stat_report, :on=>:collection
    end
    resources :orders do
      post :confirm, :paid, :cancel, :comment
      get :comment, :on => :collection
    end
    resources :payment_summaries do
      get :receive, :on => :collection
    end
    match 'users/verify' => 'users#verify'
    match 'UploadBackgroundImage' => 'home#new_background_image'
    match 'SaveBackgroundImage' => 'home#save_background_image'
    match 'clear_cache' => "settings#clear_cache"
    root :to => 'home#index'
  end

  #MERCHANT PANEL
  namespace :merchant do
    resources :home
    resources :products do
      get :sizes, :on => :collection
    end
    match ':id/coupons', :to => 'coupons#index', :as => 'coupons'
    match ':id/redeemed-coupons', :to => 'coupons#redeemed', :as => 'redeemed_coupons'
    match 'verify-coupon', :to => 'coupons#verify', :as => "coupon_verify"
    match 'merchants_orders', :to => 'report#merchants_orders', :as => "merchants_orders"
    match 'send_approval_notification', :to => 'products#send_approval_notification', :as => "send_approval_notification"
    match 'report(/:action(/:id))', :controller => 'report'
    root :to => 'home#index'
  end

  #STATIC PATH
  match 'getfeatured' => 'businesses#new'
  match 'getfeatured/submit' => 'businesses#create'
  match 'getfeatured/thanks' => 'businesses#thanks'
  match 'about' => 'home#about'
  #match 'HowAkhoniWorks' => 'home#how'
  match 'TermsOfUse' => 'home#terms'
  match 'PrivacyPolicy' => 'home#privacy'
  match 'PageNotFound' => 'home#page_not_found'
  match 'ContactUs' => 'home#contact'
  match 'InstantPurchase' => 'home#credit_card_purchase'
  match 'CashPurchase' => 'home#cash_purchase'
  match 'bkashInstruction' => 'home#bkash_instruction'
  match 'couponOnYourMobile' => 'home#coupon_on_your_mobile'
  match 'career' => 'home#jobs'
  match 'Press' => 'home#press'
  match '/notices/:id' => 'notices#show'
  match ':location/notices/:id' => 'notices#show'
  match ':location/:deal_id/free_coupon' => 'orders#free_coupon'
  match 'digital-mind-2012', :to=> 'home#digital_mind', :as => 'digital_mind'
  match 'deal-corporate-discount/:deal_id/:item_type', :to => 'deals#deal_corporate_discount', :as => "deal_corporate_discount"
  match 'product-corporate-discount/:product_id/:item_type', :to => 'products#product_corporate_discount', :as => "product_corporate_discount"
  match 'decon' => 'home#decon'

  resources :subscriptions, :unsubscribe, :notices
  resources :referrals do
    get :history, :on => :collection
  end

  #FRONT END
  resources :locations, :path => '' do
    get :determine, :on => :collection

    #PRODUCTS
    resources :products do
      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end

    resources :deals, :path => '' do
      get :index_for_facebook, :on => :collection
      get :deals, :to => :sub_deals, :on => :member
      get :past, :on => :collection
      get :expire, :on => :collection

      resources :products do
        resources :orders, {:path => 'buy'} do
          get :checkout, :coupon, :book, :print_coupon, :waiver
          resources :payments do
            post :success, :canceled, :failed, :by_mobile, :referral
            get :error, :incomplete, :invalid
          end
        end
      end

      resources :orders, {:path => 'buy'} do
        get :checkout, :coupon, :book, :print_coupon, :waiver
        resources :payments do
          post :success, :canceled, :failed, :by_mobile, :referral
          get :error, :incomplete, :invalid
        end
      end
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "locations#index"

  # See how all your routes lay out with "rake routes"
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match 'manage/orders/:id(.:format)' => 'manage/orders#comment'
  match ':controller(/:action(/:id(.:format)))'
#  match 'report(/:action(/:id))'
end

app/helpers/deals_helper.rb
module DealsHelper
  def show_price_label(deal, price_info)
    if deal.price_label.present?
      html = deal.price_label
      html = html.sub("__", "#{deal.discounted_price.to_i}".to_bddigit)
      html = html.sub("??", "#{deal.actual_price.to_i}".to_bddigit)
    else
      upto = (price_info[:original] > price_info[:original_min] &&
          price_info[:original] == price_info[:original_max])
      html = "#{t("ORIGINAL_PRICE")} #{t('UPTO') if upto} " if I18n.locale == :en
      html = "#{t("ORIGINAL_PRICE")} " if I18n.locale == :bn
      html += "<span class=\"taka\">#{price_info[:original].to_i.to_bddigit}</span> #{t("TAKA")}"
      html += " #{t('UPTO') if upto}" if I18n.locale == :bn
    end
    return html.html_safe
  end

  def show_pay(deal, price_info, page = 'show')
    html = ''
    if deal.pay_label.present?
      pay_label=deal.pay_label.split(" ")
      if (page == 'multiple_deal')
        html = deal.pay_label.downcase.to_bddigit
        html = html.gsub("#{t('PAY').downcase}", "#{t("PAY")}<br /><span>")
        html = html.gsub(/upto/, "<sup class=\"upto-tag\">upto</sup>")
        html = html.gsub(/tk./, "<small style=\"font-size: 10px;\">Tk.</small></span>")
        html = html.gsub(/taka/, "<small style=\"font-size: 10px;\">Tk.</small></span>")
        html = html.gsub('pay', t('PAY'))
      elsif (page == 'newsletter')
        html = deal.pay_label.downcase
        html = html.gsub(/pay/, "Pay<br />")
        price = deal.pay_label.gsub(/[^0-9]/, '').to_i
        price_tag = "<span style=\"font-family: 'HelveticaRoundedLTBoldCnRg',Arial,Helvetica,sans-serif; color: rgb(255, 0, 96); font-size: 30px; letter-spacing: -1px; margin-bottom: 15px;\">#{price}</span>"
        price_tag = "#{price_tag}<br />"
        html = html.gsub(/#{price}/, price_tag)
      else
        html = deal.pay_label.gsub(/[^0-9]/, '').to_i.to_bddigit.to_s
        html += "<span style=\"font-size: 14pt\"> Tk. </span>"
      end
    else
      upto = (price_info[:pay] > price_info[:pay_min] && price_info[:pay] == price_info[:pay_max])
      if (page == 'multiple_deal')
        html = "#{t('PAY')}<br /><span>"
        html += '<sup class="upto-tag">upto</sup>' if upto
        html += "#{price_info[:pay].to_i} ".to_bddigit
        html +='<small style="font-size: 10px;">Tk.</small></span>'
      elsif (page == 'newsletter')
        html += "Pay "
        html += 'Upto' if upto
        html += "<br /><span style=\"font-family: 'HelveticaRoundedLTBoldCnRg',Arial,Helvetica,sans-serif; color: rgb(255, 0, 96); font-size: 30px; letter-spacing: -1px; margin-bottom: 15px;\">#{price_info[:pay].to_i}</span> "
        html +='<br/>Taka'
      else
        html = "#{price_info[:pay].to_i}".to_bddigit
        html += "<span style='font-size: 14pt'> #{t("TAKA")}</span>"
      end
    end
    return html.html_safe
  end

  def show_discount(deal, price_info, page = 'show')
    if deal.discount_label.present?
      discount_label=deal.discount_label.split(" ")
      if (page == 'multiple_deal')
        html= "#{t('DISCOUNT')}<br/><span>"
        discount_label.each do |d|
          if d.downcase == "upto"
            html += '<sup class="upto-tag">upto</sup>'
          elsif d.downcase=="discount"
          else
            html += d.to_bddigit
          end
          html += ' '
        end
        html += '</span>'
      elsif (page == 'past')
        html = deal.discount_label.to_bddigit
      else
        saving_upto = false
        discount_label.each do |d|
          if d.downcase=="upto"
            saving_upto=true
          end
        end
        html = " <div class=\"saving #{'upto' if saving_upto}\"> "
        discount_label.each do |d|
          if d.downcase=="upto"
            html += ' <p>Upto</p> '
          elsif d.downcase == 'discount'
          else
            html += ' <p class="save"> '
            html +=d.to_bddigit
          end
          html +=' '
        end
        html += ' </p>'
        html += " <p>#{t('SAVINGS')}</p> "
        html += '</div>'
      end
    else
      upto = (price_info[:discount] > price_info[:discount_min])

      if (page == 'multiple_deal')
        html= "#{t('DISCOUNT')}<br/><span>"
        html += '<sup class="upto-tag">upto</sup>' if upto
        html += "  #{price_info[:discount].to_i}%".to_bddigit
        html += '</span>'
      elsif (page == 'past')
        html = "#{'upto' if upto} #{price_info[:discount].to_i}%".to_bddigit
      else
        html = " <div class=\"saving #{'upto' if upto}\"> "
        html += ' <p>Upto</p> ' if upto
        html += ' <p class="save"> '
        html += "  #{price_info[:discount].to_i}%".to_bddigit
        html += ' </p>'
        html += " <p>#{t('SAVINGS')}</p> "
        html += '</div>'
      end
    end
    return html.html_safe
  end

  def show_save(deal, price_info, page = 'show')
    if deal.save_label.present?
      save_label=deal.save_label.split(" ")
      html = "#{t('SAVE')}<br><span>"
      save_label.each do |s|
        if s.downcase=="upto"
          html += '<sup class="upto-tag">upto</sup>'
        elsif s.downcase=="save"
        elsif s.downcase=="tk." || s.downcase=="taka"
          html +="<small style=\"font-size: 10px;\">#{s}</small></span>"
        else
          html +=s.to_bddigit
        end
        html +=' '
      end
      html = deal.save_label.to_bddigit if page == 'past'
    else
      upto = (price_info[:save] > price_info[:save_min] &&
          price_info[:save] == price_info[:save_max])

      html = "#{t('SAVE')}<br><span>"
      html += '<sup class="upto-tag">upto</sup>' if upto
      html += " #{price_info[:save].to_i}".to_bddigit
      html += '<small style="font-size: 10px;">Tk.</small></span>'
      html = "#{'upto' if upto} #{price_info[:save].to_i.to_s.to_bddigit} Tk." if page == 'past'
    end
    return html.html_safe
  end

  def show_time_counter(deal, details = false)
    html = "<h3>";

    if deal.active?
      html += details ? t("TIME_LEFT_TO_BUY_COUPON_TWO_LINE") : t("TIME_LEFT_TO_BUY_COUPON_ONE_LINE")
      if (deal.gilt? || deal.free_coupon? || deal.free_gift?) and deal.booked?
        html += "<span id=\"closed\" class=\"sold_out\">00:00:00</span>";
      else
        html += "<span id=\"time_remaining_counter#{deal.id}\">#{image_tag("loading.gif", :size => "160x33")}</span>";
      end
    elsif deal.pending?
      html += "<span id=\"time_remaining_counter#{deal.id}\" class=\"closed\">SCHEDULED ON</span>";
      html += "<p class=\"closed\">#{show_date(deal.start_date)}</p>";
    else
      html += "<span id=\"time_remaining_counter#{deal.id}\" class=\"closed\">#{t('CLOSED_ON')}</span>";
      html += "<p class=\"closed\">#{show_date(deal.end_date)}</p>";
    end
    html += "</h3>";

    return html.html_safe
  end

  def show_avail_date(deal, details = false)
    html = "<h3>";
    html += details ? t("TIME_LEFT_TO_USE_COUPON_TWO_LINE") : t("TIME_LEFT_TO_USE_COUPON_ONE_LINE")
    html += "<span>#{show_date(deal.valid_to)}</span>";
    html += "</h3>";
    return html.html_safe
  end

  def show_buy_now_friend_button(deal)
    if (deal.active? || (deal.pending? && current_user.present? && current_user.admin?)) &&
        !deal.free_coupon? && !deal.free_gift? && !deal.sub_deals.any? && !deal.sold_out? && deal.is_pay_by_card?
      if !(deal.gilt? && (deal.products.present? || deal.booked_without_wait_count?))
        return ("<img src=\"/images/purple-gift-box1.jpg\" height=\"24px\" width=\"30px\"/>" + link_to(t("BUY_FOR_FRIEND"), new_location_deal_order_path(deal.location, deal, :gift => '1'), :class => 'buy-now-friend')).html_safe
      end
    end
  end

  def show_buy_now_button(deal)
    deal_over_link = link_to(t('DEAL_OVER'), "javascript:void(0);", :class => 'button closed')
    sold_out_link = link_to(t('SOLD_OUT'), "javascript:void(0);", :class => 'button closed')
    sub_deal_page_link = link_to(t('VIEW_DETAILS_AND_BUY'), deals_location_deal_path(deal.location, deal), :class => 'button')
    buy_now_link = link_to(t('BUY_NOW'), new_location_deal_order_path(deal.location, deal), :class => 'button')
    free_coupon_link = link_to(t('GET_FREE_COUPON'), new_location_deal_order_path(deal.location, deal), :class => 'button')
    free_gift_link = link_to(t('FREE_GIFT'), new_location_deal_order_path(deal.location, deal), :class => 'button')

    if deal.active? || (deal.pending? && current_user.present? && current_user.admin?)
      if deal.free_coupon?
        return deal_over_link if deal.booked?
        return free_coupon_link
      elsif deal.free_gift?
        return deal_over_link if deal.booked?
        return free_gift_link
      elsif deal.gilt?
        return sold_out_link if deal.booked?
        return link_to(t('VIEW_DETAILS_AND_BUY'), location_deal_products_path(deal.location, deal), :class => 'button') if deal.products.any?
        return sub_deal_page_link if deal.sub_deals.any?
        return buy_now_link
      elsif deal.sub_deals.any?
        return sub_deal_page_link
      else
        return buy_now_link
      end
    else
      return deal_over_link
    end
  end


  def show_multiple_deal_button (deal)
    target = params[:action] == 'index_for_facebook' ? '_blank' : '_self'
    if deal.active?
      if (deal.gilt? || deal.free_coupon? || deal.free_gift?) and deal.booked?
        return link_to t('VIEW_DETAILS'), location_deal_path(deal.location, deal), :class => 'button', :target => target, :title => deal.title
      else
        return link_to (deal.free_gift? ? t('VIEW_DETAILS_AND_WIN') : t('VIEW_DETAILS_AND_BUY')), location_deal_path(deal.location, deal), :class => 'button', :target => target, :title => deal.title
      end
    end
  end

  def show_address(deal)
    return "" if deal.merchant.address.nil?
    html = "<div class=\"address\">"
    html += "<b>#{t('ADDRESS')}</b><br /><span>"
    html += deal.merchant.address
    html += "</span></div>"
    return html.html_safe
  end

  def show_pay_email(deal, price_info)
    html = ''

app/views/deals/_content.html.erb
<%
   deal_url = location_deal_url(@deal.location, @deal)
%>
    <% price_info = @deal.price_information(@deal.advance_payable?) %>


    <h1 class="deal_title"><%= @deal.title %></h1>

    <div style="clear:both;"></div>
    <div class="main_deal_description">
      <%= @deal.description.to_s.html_safe %>
    </div>
    <div style="clear:both;"></div>

    <%= image_slider(@deal, :large,nil,nil,'deal fast_image') %>

    <div class="original_price">
      <% if @deal.discount > 0  %>
      <span>
      <%= show_price_label(@deal, price_info) %>
     </span>
     <% end %>
      <% if current_user && current_user.corporate_discount_of(@deal).present? %>
          <div class="corporate-extra-discount" item_id="<%= @deal.id %>" item_type="deal" max_length="57">
          </div>
      <% end %>
    </div>
    <div style="clear:both;"></div>
    <% if @deal.advance_payable? && @deal.sub_deals.empty? && !@deal.gilt? && !@deal.free_gift? && !@deal.free_coupon? %>
        <div style="margin-left: 20px;float: left;width: 200px;">Pay in advance <%= @deal.discounted_price %></div>
        <div style="clear:both;"></div>
    <% end %>
    <div class="main_deal_wrap" style="margin-top: 0">

      <div id="deal_info">

        <div>
          <div class="main_price">
            <%= show_pay(@deal, price_info) %>
          </div>
        </div>
        <div>
          <div class="saving-container">
            <% if @deal.discount > 0  %>
            <%= show_discount(@deal, price_info) %>
            <% end %>
          </div>
        </div>
<div>
  <div class="counter ">
    <%= show_time_counter(@deal, true) %>
    <%= show_avail_date(@deal, true) %>
  </div>
</div>
<div>
  <div class="buy_now" style="width:146px;">
    <%= show_buy_now_button(@deal) %>
    <%= show_buy_now_friend_button(@deal) %>
  </div>
</div>
</div>
<div style="clear:both;"></div>

<div class="deal_texts">
  <div id="deal_highlights" class="highlights">
    <h3><%= t("HIGHLIGHTS") %></h3>
    <%= @deal.highlights.to_s.html_safe %>
  </div>
  <div id="deal_conditions" class="highlights">
    <h3><%= t("CONDITIONS") %></h3>
    <%= @deal.conditions.to_s.html_safe %>
  </div>
</div>
<div style="clear:both;"></div>
<div class="line"></div>
<div class="social_media social-media-likes-featured-deal" deal_id="<%= @deal.id %>" deal_url="<%= CGI.escape(location_deal_url(@deal.location, @deal)) %>">
</div>

</div>
<!-- End main_deal -->

app/views/deals/_deal_for_facebook.html.erb
<% deal = deal_for_facebook %>
<% price_info = deal.price_information %>
<div class="multiple-deal" style="width:520px">
  <div class="multiple-deal-wrap">
    <div class="multiple-deal-content">
      <h2 class="multiple-deal-title" style='font-size:12pt'>
        <%= deal.title %>: <span><%= deal.description.to_s.html_safe %></span>
      </h2>

      <div style="clear:both;"></div>
      <table cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td class="img-medium" style="height:175px;width:330px">
            <%= image_slider(deal, :medium, 330, 175, '') %>
          </td>
          <td style="vertical-align:top;">
            <div>
              <div class="multiple-deal-original" style="height:15px;padding:5px;font-size:8pt">
                <%= show_price_label(deal, price_info) %>
              </div>
              <div style="clear:both;"></div>
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="multiple-deal-price" style="font-size:9pt">
                    <%= show_pay(deal, price_info, 'multiple_deal') %>
                  </td>
                  <td style="width: 2%;"></td>
                  <td class="multiple-deal-price" style="font-size:9pt">
                    <%= show_discount(deal, price_info, 'multiple_deal') %>
                  </td>
                  <td style="width: 2%;"></td>
                  <td class="multiple-deal-price"style="font-size:9pt">
                    <%= show_save(deal, price_info) %>
                  </td>
                </tr>
                <tr>
                  <td colspan="5" class="counter" style="height:20px;font-size:8pt"><%= show_time_counter(deal) %></td>
                </tr>
                <tr>
                  <td colspan="5" class="counter" style="height:20px;font-size:8pt"><%= show_avail_date(deal) %></td>
                </tr>
                <tr>
                  <td style="text-align:center" colspan="5">
                    <%= show_multiple_deal_button(deal) %>
                  </td>
                </tr>
              </table>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

<% if deal.active? and !(deal.gilt? and deal.booked?) %>
    <script type="text/javascript">
        displayCountdown("<%=h deal.id%>", "<%=(deal.end_date.to_i - Time.now.to_i)%>", "time_remaining_counter<%=h deal.id%>")
    </script>
<% end %>

app/views/deals/_left_sidebar.html.erb
<%= render :partial => 'layouts/notice' %>

<div class="lightbox" title="Click to see details">
  <a class="iframe" href="/InstantPurchase" style="display: inline-block;margin-left: 40px;">
    <%= image_tag "/images/We-Accept-#{I18n.locale}.png", :border => 0 %>
  </a>
</div>


<div id="fb_like_box" class="left_box" style="background: white;"></div>

<div class="lightbox" title="Click to see details">
  <a class="iframe" href="/couponOnYourMobile" style="display: inline-block;margin-left: 40px;" >
    <%= image_tag "/images/Coupon-on-your-mobile-phone-#{I18n.locale}.png",  :border => 0 %>
  </a>
</div>

app/views/deals/_page_bottom.html.erb
<div class="location">
  <h2 class="map"><%= @deal.merchant.name %></h2>

  <div class="deal_background" style="float: left; width: 300px;">
    <%= @deal.background.html_safe if @deal.background.present? %>
  </div>
  <div style="float: right; width: 330px; margin-right: 10px">
    <div id="google_map" style="float: right; width: 330px;" deal_id="<%= @deal.id %>"></div>
    <div style="float: left; width: 330px;"><%= show_address(@deal) %></div>
    <div class="website"><%= link_to(@deal.merchant.website, @deal.merchant.website, :target => '_blank') if @deal.merchant.website.present? %></div>
  </div>
</div>

<div class="location" style="height:auto;">
  <h2 class="map">Comment</h2>
  <div style="float:left;margin:20px 0 0 10px;width:640px">
    <fb:comments href="<%= request.url %>" num_posts="2" width="645"></fb:comments>
  </div>
</div>

app/views/deals/_past_deal.html.erb
<% price_information = deal.price_information %>
<table cellpadding="0" cellspacing="0" border="0" width="100%" class="deal_details">
  <tr>
    <td class="image" rowspan="3">
      <%= show_picture(deal, :medium) %>
    </td>
  </tr>
  <tr>
    <td class="content">
      <table cellpadding="0" cellspacing="0" border="0" width="100%">
        <tr>
          <td class="deal-title top">
            <h4><%= link_to h(deal.title), location_deal_path(deal.location, deal) %></h4>
          </td>
        </tr>
        <tr>
          <td class="desc">
            <%= deal.description.to_s.html_safe %>
          </td>
        </tr>
        <% unless (deal.free_coupon? || deal.free_gift?) %>
          <tr>
            <td><span class="label"><i><%=show_price_label(deal, price_information) %></i></span></td>
          </tr>
        <% end %>
        <tr>
          <td><span class="label"><%= t('DISCOUNT')%> :</span> <%= show_discount(deal, price_information, 'past') %></td>
        </tr>
        <% unless (deal.free_coupon? || deal.free_gift?) %>
          <tr>
            <td><span class="label"><%= t('SAVINGS')%>  :</span> <%= show_save(deal, price_information, 'past') %></td>
          </tr>
        <% end %>
        <tr>
          <td><span class="label"><%= t('CLOSED_ON')%> :</span> <%= show_date(deal.end_date) %></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td class="link">
      <fb:like href="<%= location_deal_url(deal.location, deal) %>" send="false" width="50" show_faces="false" font="" layout="button_count"></fb:like>
      <!--<a name="fb_share" class="social-button" type="button_count" share_url="<%= location_deal_url(deal.location, deal) %>" href="http://www.facebook.com/sharer.php">Share</a>-->
      <%= link_to(t("VIEW_DETAILS"), location_deal_path(deal.location, deal)) %>
    </td>
  </tr>
</table>

app/views/deals/_recent_deals.html.erb
<% if deals.present? && deals.size > 0 %>
    <ul class="side-deals">
      <li class="header"><h3><%= link_to t("RECENT_DEALS"), past_location_deals_path(session[:location]) %></h3></li>
      <%= render :partial => 'side_deal', :collection => deals, :as => :deal %>
      <li class="bangla" style="border-top: 1px solid #000000"><%= link_to t("VIEW_ALL_RECENT_DEALS"), past_location_deals_path(session[:location]), :style => "color: #5A0E3C" %></li>
      <li class="last"> </li>
    </ul>
<% end %>

app/views/deals/_side_deal.html.erb
<li class="deal">
  <h4><%= link_to h(deal.title), location_deal_path(deal.location, deal) %></h4>
  <table cellpadding="0" cellspacing="0" width="100%">
    <tr>
      <td><%= show_picture(deal, :small) %></td>
      <td align="center" valign="middle">
        <%=show_discount(deal,deal.price_information) %>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="deal-content">
        <%= deal.description.to_s.html_safe %>
        <%= link_to(t('VIEW_MORE'), location_deal_path(deal.location, deal)) %>
      </td>
    </tr>
  </table>
</li>

app/views/deals/_side_deals.html.erb
<% if @left_widget.present? && @left_widget[:deals].size > 0 %>
    <ul class="side-deals">
      <li class="header"><h3><%= h @left_widget[:title].html_safe %></h3></li>
      <%= render :partial => 'side_deal', :collection => @left_widget[:deals], :as => :deal %>
      <li class="last"> </li>
    </ul>
<% end %>

app/views/deals/index.html.erb
<%= render_featured_deals %>

<% cache "featured-merchants-#{I18n.locale}" do %>
    <%= render_featured_merchants() %>
<% end %>


<% if params[:category_id].to_i != 1 %>
    <% cache "featured-travels-#{I18n.locale}" do %>
        <%= render_featured_travels() %>
    <% end %>
<% end %>


<% cache "featured-products-#{I18n.locale}" do %>
    <%= render_featured_products() %>
<% end %>

<%#= render :partial => 'more_deals' %>

<% content_for :left_sidebar do %>
    <%#= render :partial => 'left_sidebar' %>

    <div class="noprint" title="Click to see details">
      <a class="" href="/digital-mind-2012" style="display: inline-block;margin-left: 40px;" >
        <%= image_tag "/images/digital-mind-2012.png",  :border => 0 %>
      </a>
    </div>

    <% cache "recent-deals-#{I18n.locale}"  do%>
        <%#= render_recent_deals %>
    <% end %>
<% end %>

app/views/deals/sub_deals.html.erb
<div class="sub-deal-container">
  <h1 class="deal_title">
    <%= link_to(@deal.title, location_deal_path(@deal.location, @deal)) %>
  </h1>

  <div style="clear:both;"></div>
  <br/>

  <%= render :partial => 'sub_deals' %>
</div>